### ISSUE TITLE
Improve cli interface

### ISSUE THREAD

**Issue by sk-** [Instagram/Fixit#167]
- [ ] Add a way to disable the `RemoveUnusedSuppressionsRule`
- [ ] Standardize the flag for enabling disabling ignore comments. `apply_fix` uses `get_skip_ignore_comments_parser`, but `run_rules` uses `get_use_ignore_comments_parser`, which has `True` as a default, meaning it's impossible to disable it.

**Comment by amyreese** [comment]
Hey folks, we just released Fixit 2.0, which includes major changes to the core frameworks, linting engine, API, and CLI. In light of this new release, this issue is likely to be resolved or no longer relevant. Please take a look at the new [user guide](https://fixit.readthedocs.io/en/latest/guide.html#) or the [upgrade guide](https://fixit.readthedocs.io/en/latest/upgrade.html) for more information on how to migrate your projects to the new version.

If you believe this issue is still relevant or still occurring in the latest version, please feel free to open a new issue, or reply here with more details.

Thank you!
