### ISSUE TITLE
Change should_skip_file to not require the MetadataWrapper

### ISSUE THREAD

**Issue by sk-** [Instagram/Fixit#168]
Today `should_skip_file` is an instance method and hence requires the metadata wrapper, which in turn requires to parse the code.

However, the two rules defining this method, only use the file name and the config.

It would be ideal if we could change it so that the check could be performed without having to parse the code.

For example to speed up the linting I want to just use the `_source` (I know it's private now) checking if it matches a very simplified regex (note: this regex would be autogenerated).

**Comment by amyreese** [comment]
Hey folks, we just released Fixit 2.0, which includes major changes to the core frameworks, linting engine, API, and CLI. In light of this new release, this issue is likely to be resolved or no longer relevant. Please take a look at the new [user guide](https://fixit.readthedocs.io/en/latest/guide.html#) or the [upgrade guide](https://fixit.readthedocs.io/en/latest/upgrade.html) for more information on how to migrate your projects to the new version.

If you believe this issue is still relevant or still occurring in the latest version, please feel free to open a new issue, or reply here with more details.

Thank you!
