### ISSUE TITLE
apply_fix is too slow

### ISSUE THREAD

**Issue by sk-** [Instagram/Fixit#169]
Currently apply_fix is too slow. I reckon this is due to the fact that if a file has many violations, the linter will be run as many times. For LibCST it too several minutes to just fix one of the affected files.

The code says:

> Applying a single fix at a time prevents the scenario where multiple autofixes combine in a way that results in invalid code.

What do you think of applying all the fixes with disjoint line ranges?

**Comment by amyreese** [comment]
Hey folks, we just released Fixit 2.0, which includes major changes to the core frameworks, linting engine, API, and CLI. In light of this new release, this issue is likely to be resolved or no longer relevant. Please take a look at the new [user guide](https://fixit.readthedocs.io/en/latest/guide.html#) or the [upgrade guide](https://fixit.readthedocs.io/en/latest/upgrade.html) for more information on how to migrate your projects to the new version.

If you believe this issue is still relevant or still occurring in the latest version, please feel free to open a new issue, or reply here with more details.

Thank you!
