### ISSUE TITLE
unrecognized arguments: --use-ignore-comments

### ISSUE THREAD

**Issue by anilbey** [Instagram/Fixit#219]
Hi, 
This docs page mentions `use-ignore-comments`. Yet `fixit run-rules` does not recognise it.
Was there an update?

docs
`https://fixit.readthedocs.io/en/latest/test_a_lint_rule.html?highlight=use-ignore-comments#Run-Your-Rule-in-a-Codebase
`

example
```
> fixit run_rules . --use-ignore-comments
usage: fixit [-h] [--version] {add_new_rule,apply_fix,insert_suppressions,run_rules} ...
fixit: error: unrecognized arguments: --use-ignore-comments
```

**Comment by amyreese** [comment]
Hey folks, we just released Fixit 2.0, which includes major changes to the core frameworks, linting engine, API, and CLI. In light of this new release, this issue is likely to be resolved or no longer relevant. Please take a look at the new [user guide](https://fixit.readthedocs.io/en/latest/guide.html#) or the [upgrade guide](https://fixit.readthedocs.io/en/latest/upgrade.html) for more information on how to migrate your projects to the new version.

If you believe this issue is still relevant or still occurring in the latest version, please feel free to open a new issue, or reply here with more details.

Thank you!
